import json, os

preguntas = [
    # ===================== RONDA VELOZ (20) =====================
    {"id":1,"ronda":"veloz","categoria":"historia","pregunta":"¿Cuál fue la primera universidad fundada en Castilla y León?","opciones":["Universidad de Salamanca","Universidad de Palencia","Universidad de Valladolid","Universidad de Burgos"],"correcta":"B","dificultad":2,"dato":"La Universidad de Palencia, fundada por Alfonso VIII hacia 1208-1212, fue la primera de Castilla y León.","tiempo":10},
    {"id":2,"ronda":"veloz","categoria":"monumentos","pregunta":"¿Qué famoso escultor creó el Cristo del Otero de Palencia?","opciones":["Eduardo Barrón","Victorio Macho","Mariano Benlliure","Emilio Calist"],"correcta":"B","dificultad":1,"dato":"Victorio Macho esculpió el Cristo del Otero en 1930. Con 21 metros, es una de las estatuas de Cristo más grandes del mundo.","tiempo":10},
    {"id":3,"ronda":"veloz","categoria":"gastronomia","pregunta":"¿Qué plato estrella de la gastronomía palentina se asa en horno de leña?","opciones":["Cochinillo","Lechazo","Cordero al chilindrón","Cabrito"],"correcta":"B","dificultad":1,"dato":"El lechazo asado en horno de leña es el plato más emblemático de Palencia, especialmente en la comarca de Tierra de Campos.","tiempo":10},
    {"id":4,"ronda":"veloz","categoria":"historia","pregunta":"¿Qué rey fundó la Universidad de Palencia?","opciones":["Alfonso X el Sabio","Alfonso VIII","Fernando III","Sancho IV"],"correcta":"B","dificultad":2,"dato":"Alfonso VIII de Castilla fundó el Estudio General de Palencia, considerado la primera universidad de Castilla y León.","tiempo":10},
    {"id":5,"ronda":"veloz","categoria":"geografia","pregunta":"¿Qué río principal atraviesa la ciudad de Palencia?","opciones":["Río Pisuerga","Río Carrión","Río Duero","Río Esla"],"correcta":"B","dificultad":1,"dato":"El río Carrión atraviesa Palencia capital. El Pisuerga también pasa por la provincia pero no por la capital.","tiempo":10},
    {"id":6,"ronda":"veloz","categoria":"monumentos","pregunta":"¿De qué estilo arquitectónico es la Iglesia de San Miguel de Palencia?","opciones":["Gótico","Barroco","Románico","Mudéjar"],"correcta":"C","dificultad":1,"dato":"San Miguel es uno de los mejores ejemplos del románico palentino, con una portada spectacular y un rosetón único.","tiempo":10},
    {"id":7,"ronda":"veloz","categoria":"naturaleza","pregunta":"¿Qué parque natural se encuentra al norte de la provincia de Palencia?","opciones":["Parque natural de Fuentes Carrionas y Fuente Cobre-Montaña Palentina","Parque natural de las Hoces del Duratón","Parque natural de Redes","Parque natural de Picos de Europa"],"correcta":"A","dificultad":1,"dato":"Fuentes Carrionas y Fuente Cobre-Montaña Palentina es el único parque natural de la provincia.","tiempo":10},
    {"id":8,"ronda":"veloz","categoria":"gastronomia","pregunta":"¿Qué embutido es típico de la localidad palentina de Astudillo?","opciones":["Chorizo","Morcilla","Salchichón","Lomo embuchado"],"correcta":"B","dificultad":2,"dato":"La morcilla de Palencia, especialmente la de Astudillo, es un embutido tradicional con cebolla y especias.","tiempo":10},
    {"id":9,"ronda":"veloz","categoria":"geografia","pregunta":"¿En qué comarca se encuentra Aguilar de Campoo?","opciones":["Tierra de Campos","Montaña Palentina","Vega-Valdavia","Boedo-Ojeda"],"correcta":"B","dificultad":1,"dato":"Aguilar de Campoo es la localidad más importante de la comarca de Montaña Palentina, norte de la provincia.","tiempo":10},
    {"id":10,"ronda":"veloz","categoria":"historia","pregunta":"¿Qué vía de comunicación histórica atraviesa la provincia de Palencia de este a oeste?","opciones":["Vía de la Plata","Canal de Castilla","Ruta de la Lana","Camino del Norte"],"correcta":"B","dificultad":2,"dato":"El Canal de Castilla, construido en el s. XVIII, atraviesa la provincia de Palencia con sus tres ramales.","tiempo":10},
    {"id":11,"ronda":"veloz","categoria":"personajes","pregunta":"¿Qué santo patrono de Palencia fue obispo de la diócesis en el siglo VII?","opciones":["San Antolín","San Pedro","San Pablo","San Zoilo"],"correcta":"A","dificultad":2,"dato":"San Antolín (o San Antolino) es el patrón de Palencia. Las fiestas patronales se celebran el 2 de septiembre.","tiempo":10},
    {"id":12,"ronda":"veloz","categoria":"tradiciones","pregunta":"¿Qué tradición palentina consiste en decorar con ramas las ventanas de las mozas?","opciones":["Las Enramadas","Los Mayos","La Procesión del Santo Entierro","La Loa"],"correcta":"A","dificultad":2,"dato":"Las Enramadas de Palencia se celebran en la madrugada del 30 de abril al 1 de mayo, decorando ventanas con ramas.","tiempo":10},
    {"id":13,"ronda":"veloz","categoria":"naturaleza","pregunta":"¿Qué especie bovina autóctona se cría en la Montaña Palentina?","opciones":["Vaca Frisona","Vaca Tudanca","Vaca Retinta","Vaca Limusina"],"correcta":"B","dificultad":2,"dato":"La vaca Tudanca es una raza autóctona de Cantabria y la Montaña Palentina, adaptada al clima duro de la zona.","tiempo":10},
    {"id":14,"ronda":"veloz","categoria":"geografia","pregunta":"¿Cuál es la provincia limítrofe al SUR de Palencia?","opciones":["Valladolid","Burgos","León","Zamora"],"correcta":"A","dificultad":1,"dato":"Al sur de Palencia limita con la provincia de Valladolid. También limita con Burgos (este), León (oeste) y Cantabria (norte).","tiempo":10},
    {"id":15,"ronda":"veloz","categoria":"monumentos","pregunta":"¿Qué edificio religioso de Palencia tiene una de las torres más altas de España?","opciones":["Catedral de Palencia","Iglesia de San Miguel","Monasterio de San Zoilo","Iglesia de San Pablo"],"correcta":"A","dificultad":2,"dato":"La Catedral de Palencia, llamada 'la desconocida', tiene una torre de 55 metros, una de las más altas entre las catedrales españolas.","tiempo":10},
    {"id":16,"ronda":"veloz","categoria":"cultura_pop","pregunta":"¿Qué película de Disney se inspiró parcialmente en el paisaje de Tierra de Campos palentina?","opciones":["Brave","Tangled","Frozen","Moana"],"correcta":"A","dificultad":3,"dato":"El equipo de Disney Pixar visitó Tierra de Campos para documentarse en la creación de Brave (2012), inspirándose en sus paisajes castellanos.","tiempo":10,"verificar":true},
    {"id":17,"ronda":"veloz","categoria":"deportes","pregunta":"¿Qué equipo de fútbol de Palencia jugó en Segunda División B?","opciones":["CF Palencia","CD Palencia Balompié","Atlético Palencia","UD Palencia"],"correcta":"A","dificultad":2,"dato":"El Club de Fútbol Palencia jugó varias temporadas en Segunda División B antes de su desaparición en 2012.","tiempo":10},
    {"id":18,"ronda":"veloz","categoria":"historia","pregunta":"¿En qué siglo se construyó el Canal de Castilla?","opciones":["Siglo XVI","Siglo XVII","Siglo XVIII","Siglo XIX"],"correcta":"C","dificultad":2,"dato":"El Canal de Castilla se comenzó a construir en 1753, durante el reinado de Fernando VI, en el siglo XVIII.","tiempo":10},
    {"id":19,"ronda":"veloz","categoria":"monumentos","pregunta":"¿Qué monasterio situado junto al Canal de Castilla es un hotel-parador?","opciones":["Monasterio de San Zoilo","Monasterio de San Antolín","Monasterio de la Trinidad","Monasterio de Santa Clara"],"correcta":"A","dificultad":2,"dato":"El Monasterio de San Zoilo en Carrión de los Condes es un hotel-parador situado junto al Canal de Castilla.","tiempo":10},
    {"id":20,"ronda":"veloz","categoria":"gastronomia","pregunta":"¿Qué postre típico palentino se hace con yemas de huevo y almendra?","opciones":["Yemas de Palencia","Perrunillas","Hojuelas","Tarta de Castilla"],"correcta":"A","dificultad":2,"dato":"Las Yemas de Palencia (o Yemas de Santa Teresa) son un dulce tradicional elaborado con yemas de huevo y azúcar.","tiempo":10},

    # ===================== RONDA IMAGEN (15) =====================
    {"id":21,"ronda":"imagen","categoria":"monumentos","pregunta":"Se ve una enorme figura blanca de Cristo sobre una colina, con los brazos abiertos, dominando una ciudad llana. ¿De qué monumento se trata?","opciones":["Cristo del Otero (Palencia)","Cristo de la Concordia (Bolivia)","Cristo Rey (Lisboa)","Cristo de Corcovado (Río)"],"correcta":"A","dificultad":1,"dato":"El Cristo del Otero, obra de Victorio Macho (1930), mide 21 metros y domina la ciudad de Palencia desde el cerro del Otero.","tiempo":15},
    {"id":22,"ronda":"imagen","categoria":"monumentos","pregunta":"Una iglesia románica con una elegante portada de arquivoltas y un gran rosetón central en la fachada, en pleno casco urbano. ¿Qué iglesia es?","opciones":["Iglesia de San Miguel (Palencia)","Catedral de León","Iglesia de Santa María (Fromista)","Colegiata de San Pedro (Cervatos)"],"correcta":"A","dificultad":2,"dato":"La Iglesia de San Miguel es el edificio románico más importante de Palencia capital, destacando su portada y rosetón.","tiempo":15},
    {"id":23,"ronda":"imagen","categoria":"monumentos","pregunta":"Un enorme castillo en ruinas sobre una peña rodeada de agua, en un embalse. Pertenece a una villa del norte de Palencia. ¿Cuál?","opciones":["Castillo de Aguilar de Campoo","Castillo de la Mota (Medina)","Castillo de Ponferrada","Castillo de Gormaz"],"correcta":"A","dificultad":2,"dato":"El Castillo de Aguilar de Campoo se alza sobre una peña rodeada por las aguas del embalse de Aguilar.","tiempo":15},
    {"id":24,"ronda":"imagen","categoria":"naturaleza","pregunta":"Un canal de agua recto y largo entre árboles, con esclusas de piedra, cruzando una llanura. ¿Qué infraestructura hidráulica es?","opciones":["Canal de Castilla","Canal Imperial de Aragón","Canal del Duero","Acueducto de Segovia"],"correcta":"A","dificultad":1,"dato":"El Canal de Castilla recorre más de 200 km por las provincias de Palencia, Burgos y Valladolid.","tiempo":15},
    {"id":25,"ronda":"imagen","categoria":"monumentos","pregunta":"Una catedral gótica de grandes dimensiones con una torre imponente, apodada 'la desconocida'. ¿De qué ciudad?","opciones":["Palencia","Burgos","León","Oviedo"],"correcta":"A","dificultad":2,"dato":"La Catedral de Palencia (Catedral de San Antolín) es apodada 'la desconocida' por su belleza poco difundida. Tiene 130 metros de longitud.","tiempo":15},
    {"id":26,"ronda":"imagen","categoria":"monumentos","pregunta":"Una iglesia románica perfecta en un pequeño pueblo, con una torre cilíndrica y decoración escultórica excepcional. Es la colegiata de...","opciones":["San Pedro de Cervatos","Santa María de Fromista","San Martín de Frómista","San Juan de Baños"],"correcta":"C","dificultad":2,"dato":"La iglesia de San Martín de Frómista es uno de los mejores ejemplos del románico pleno de España.","tiempo":15},
    {"id":27,"ronda":"imagen","categoria":"monumentos","pregunta":"Un puente medieval de piedra con muchos arcos sobre un río, en una villa jacobea importante. ¿Qué puente es?","opciones":["Puente de Carrión de los Condes","Puente de Burgos","Puente de Ponferrada","Puente de Mansilla"],"correcta":"A","dificultad":2,"dato":"El Puente de Carrión de los Condes, del s. X, tiene 11 arcos y es uno de los más impresionantes del Camino de Santiago.","tiempo":15},
    {"id":28,"ronda":"imagen","categoria":"monumentos","pregunta":"Una pequeña iglesia prerrománica del siglo VII, mandada construir por un rey visigodo, cerca de Palencia capital. ¿Cuál?","opciones":["San Juan de Baños","Santa Comba de Bande","San Pedro de la Nave","Quintanilla de las Viñas"],"correcta":"A","dificultad":3,"dato":"La iglesia de San Juan de Baños fue mandada construir por el rey visigodo Recesvinto en el año 661.","tiempo":15},
    {"id":29,"ronda":"imagen","categoria":"naturaleza","pregunta":"Un paisaje de montaña con lagos glaciares, bosques de hayas y picos de más de 2.000 metros al norte de Palencia. ¿Qué parque natural?","opciones":["Fuentes Carrionas y Fuente Cobre","Picos de Europa","Parque Natural de Redes","Sierra de Gredos"],"correcta":"A","dificultad":1,"dato":"Fuentes Carrionas y Fuente Cobre-Montaña Palentina acoge picos como Curavacas (2.525 m) y lagos glaciares.","tiempo":15},
    {"id":30,"ronda":"imagen","categoria":"monumentos","pregunta":"Un monasterio cluniacense junto a un río, con una portada románica espectacular, en la localidad de Fromista. ¿Cuál?","opciones":["Monasterio de San Zoilo","Monasterio de las Huelgas","Monasterio de San Salvador de Nogal","Iglesia de San Martín"],"correcta":"A","dificultad":3,"dato":"El Monasterio de San Zoilo está en Carrión de los Condes, no en Frómista. La iglesia románica más famosa de Frómista es San Martín.","tiempo":15,"verificar":true},
    {"id":31,"ronda":"imagen","categoria":"monumentos","pregunta":"Un gran edificio renacentista con patio columnado, sede de la Diputación de Palencia. ¿Cómo se llama?","opciones":["Palacio de la Diputación","Casa del Cordón","Palacio de los Condes de Buendía","Palacio del Almirante"],"correcta":"A","dificultad":2,"dato":"El Palacio de la Diputación de Palencia es un edificio renacentista del s. XVI situado en la plaza Mayor.","tiempo":15},
    {"id":32,"ronda":"imagen","categoria":"monumentos","pregunta":"Una ermita barroca de planta octogonal en lo alto de un cerro, junto al Cristo del Otero. ¿Cómo se llama?","opciones":["Ermita de la Soledad","Ermita del Santo Cristo","Ermita de San Juan","Ermita de la Vera Cruz"],"correcta":"A","dificultad":3,"dato":"Junto al Cristo del Otero se encuentra la ermita de la Soledad, de estilo barroco y planta hexagonal.","tiempo":15,"verificar":true},
    {"id":33,"ronda":"imagen","categoria":"naturaleza","pregunta":"Un embalse rodeado de montañas verdes en la Montaña Palentina, ideal para deportes acuáticos. Es el embalse de...","opciones":["Embalse de Aguilar","Embalse de Riaño","Embalse del Porma","Embalse de Ricobayo"],"correcta":"A","dificultad":2,"dato":"El Embalse de Aguilar, sobre el río Pisuerga, es uno de los mayores de Castilla y León y un destino turístico importante.","tiempo":15},
    {"id":34,"ronda":"imagen","categoria":"monumentos","pregunta":"Una casa solariega del s. XVI con una fachada de sillería y escudo nobiliario, típica de la arquitectura de Carrión de los Condes. ¿Qué tipo de edificio?","opciones":["Casa solariega o palacio renacentista","Castillo medieval","Iglesia fortificada","Torre de homenaje"],"correcta":"A","dificultad":2,"dato":"Carrión de los Condes conserva numerosas casas solariegas y palacios renacentistas con escudos nobiliarios.","tiempo":15},
    {"id":35,"ronda":"imagen","categoria":"monumentos","pregunta":"Una gran plaza porticada con soportales de madera y piedra, centro neurálgico de Palencia capital. Es la plaza...","opciones":["Plaza Mayor","Plaza de la Inmaculada","Plaza del Dos de Mayo","Plaza de San Pablo"],"correcta":"A","dificultad":1,"dato":"La Plaza Mayor de Palencia, con sus soportales y el edificio del Ayuntamiento, es el centro de la ciudad.","tiempo":15},

    # ===================== RONDA CURIOSIDADES (15) =====================
    {"id":36,"ronda":"curiosidades","categoria":"datos_insolitos","pregunta":"¿Por qué a la Catedral de Palencia se la conoce como 'la desconocida'?","opciones":["Por su tamaño escondido tras otros edificios","Porque siendo la 3ª más grande de España, pocos la conocen","Porque estuvo enterrada siglos","Porque su entrada es difícil de encontrar"],"correcta":"B","dificultad":2,"dato":"La Catedral de Palencia es la tercera más grande de España tras Sevilla y Toledo, pero es poco conocida fuera de la provincia.","tiempo":15},
    {"id":37,"ronda":"curiosidades","categoria":"historia","pregunta":"¿Qué connection tiene el Camino de Santiago con la provincia de Palencia?","opciones":["El Camino Francés pasa por Palencia capital","El Camino Francés pasa por Carrión de los Condes y Frómista","Solo pasa el Camino del Norte","No pasa ningún Camino por Palencia"],"correcta":"B","dificultad":2,"dato":"El Camino de Santiago Francés atraviesa Palencia por localidades como Itero de la Vega, Frómista, Carrión de los Condes y Calzadilla de la Cueza.","tiempo":15},
    {"id":38,"ronda":"curiosidades","categoria":"datos_insolitos","pregunta":"¿Cuántos metros mide el Cristo del Otero de Palencia?","opciones":["15 metros","18 metros","21 metros","25 metros"],"correcta":"C","dificultad":2,"dato":"El Cristo del Otero mide 21 metros de altura, siendo una de las estatuas de Cristo más grandes del mundo, superada por pocas.","tiempo":15},
    {"id":39,"ronda":"curiosidades","categoria":"historia","pregunta":"¿Qué importante concilio se celebró en tierras palentinas en el siglo XI?","opciones":["Concilio de Letrán","Concilio de Carrión","Concilio de Clermont","Concilio de Toledo"],"correcta":"B","dificultad":3,"dato":"En Carrión de los Condes se celebraron concilios importantes en la Edad Media, como el de 1104.","tiempo":15,"verificar":true},
    {"id":40,"ronda":"curiosidades","categoria":"gastronomia","pregunta":"¿Cuál es la peculiaridad de la morcilla de Palencia respecto a otras morcillas españolas?","opciones":["Lleva chocolate","Se hace sin sangre","Lleva cebolla y pimentón dulce","Es blanca, sin especias"],"correcta":"C","dificultad":2,"dato":"La morcilla de Palencia se caracteriza por llevar cebolla, pimentón dulce y especias, dándole un sabor distintivo.","tiempo":15},
    {"id":41,"ronda":"curiosidades","categoria":"datos_insolitos","pregunta":"¿Qué pintor español nació en la localidad palentina de Velillas de la Coca?","opciones":["Velázquez","Goya","El Greco","Ninguno de los anteriores nació ahí"],"correcta":"D","dificultad":3,"dato":"Ninguno de los pintores mencionados nació en esa localidad palentina. Velillas de la Coca es un pequeño pueblo de la provincia.","tiempo":15,"verificar":true},
    {"id":42,"ronda":"curiosidades","categoria":"naturaleza","pregunta":"¿Cuál es el pico más alto de la provincia de Palencia?","opciones":["Pico Curavacas","Pico Espigüete","Peña Prieta","Pico Tres Mares"],"correcta":"A","dificultad":3,"dato":"El Pico Curavacas, con 2.525 metros, es la cima más alta de la provincia de Palencia.","tiempo":15},
    {"id":43,"ronda":"curiosidades","categoria":"historia","pregunta":"El Canal de Castilla tiene tres ramales. ¿Cuál NO es uno de ellos?","opciones":["Ramal Norte","Ramal Sur","Ramal de Campos","Ramal de Castilla"],"correcta":"D","dificultad":3,"dato":"Los tres ramales del Canal de Castilla son: Ramal Norte, Ramal Sur y Ramal de Campos.","tiempo":15},
    {"id":44,"ronda":"curiosidades","categoria":"datos_insolitos","pregunta":"¿Qué famoso explorador del siglo XVI era natural de la provincia de Palencia?","opciones":["Hernán Cortés","Francisco Pizarro","Fray Bernardino de Sahagún","Ninguno de los mencionados"],"correcta":"C","dificultad":3,"dato":"Fray Bernardino de Sahagún, misionero y etnógraico que documentó la cultura azteca, era natural de Sahagún (León), cerca de la frontera con Palencia.","tiempo":15,"verificar":true},
    {"id":45,"ronda":"curiosidades","categoria":"tradiciones","pregunta":"¿En qué mes se celebran Las Enramadas en Palencia?","opciones":["Marzo","Abril","Mayo","Junio"],"correcta":"C","dificultad":2,"dato":"Las Enramadas se celebran en la noche del 30 de abril al 1 de mayo, aunque los festejos se extienden durante varios días.","tiempo":15},
    {"id":46,"ronda":"curiosidades","categoria":"historia","pregunta":"¿Qué nombre romano recibía la actual ciudad de Palencia?","opciones":["Pallantia","Caesar Augusta","Asturica Augusta","Pintia"],"correcta":"A","dificultad":2,"dato":"Los romanos llamaban Pallantia a la actual Palencia. Fue un importante núcleo en la Hispania Tarraconensis.","tiempo":15},
    {"id":47,"ronda":"curiosidades","categoria":"datos_insolitos","pregunta":"¿Cuántos kilómetros tiene aproximadamente el Canal de Castilla?","opciones":["75 km","130 km","207 km","300 km"],"correcta":"C","dificultad":2,"dato":"El Canal de Castilla tiene una longitud total de aproximadamente 207 kilómetros.","tiempo":15},
    {"id":48,"ronda":"curiosidades","categoria":"personajes","pregunta":"¿Qué escritora palentina recibió el Premio Nadal en 1959?","opciones":["Carmen Laforet","Ana María Matute","Carmen Martín Gaite","Elena Quiroga"],"correcta":"D","dificultad":3,"dato":"Elena Quiroga, nacida en Vega de Peridiello (Santander) pero vinculada a Palencia, recibió el Premio Nadal en 1959 por 'Viento del norte'.","tiempo":15,"verificar":true},
    {"id":49,"ronda":"curiosidades","categoria":"datos_insolitos","pregunta":"¿Cuántos habitantes tiene aproximadamente la provincia de Palencia?","opciones":["100.000","160.000","250.000","400.000"],"correcta":"B","dificultad":2,"dato":"La provincia de Palencia tiene aproximadamente 160.000 habitantes, siendo una de las menos pobladas de España.","tiempo":15},
    {"id":50,"ronda":"curiosidades","categoria":"naturaleza","pregunta":"¿Qué tipo de árbol es emblemático de la comarca de Tierra de Campos palentina?","opciones":["Olivo","Encina","Pino","Roble"],"correcta":"B","dificultad":2,"dato":"La encina es el árbol más característico de Tierra de Campos, aunque también son típicos los chopos junto a los ríos.","tiempo":15},

    # ===================== RONDA PALENCIA PROFUNDA (15) =====================
    {"id":51,"ronda":"profunda","categoria":"historia","pregunta":"¿En qué año exacto se iniciaron las obras del Canal de Castilla?","opciones":["1749","1753","1758","1762"],"correcta":"B","dificultad":3,"dato":"Las obras del Canal de Castilla comenzaron en 1753, bajo el reinado de Fernando VI, impulsadas por el marqués de la Ensenada.","tiempo":20},
    {"id":52,"ronda":"profunda","categoria":"monumentos","pregunta":"¿Cuántas esclusas tiene el Canal de Castilla en el tramo palentino?","opciones":["15 esclusas","24 esclusas","32 esclusas","49 esclusas"],"correcta":"D","difultad":3,"dato":"El Canal de Castilla tiene un total de 49 esclusas en todo su recorrido, de las cuales muchas se encuentran en la provincia de Palencia.","tiempo":20,"verificar":true},
    {"id":53,"ronda":"profunda","categoria":"historia","pregunta":"¿Qué batalla del siglo XIX tuvo lugar cerca de Palencia durante la Guerra de la Independencia?","opciones":["Batalla de Bailén","Batalla de Medina de Rioseco","Batalla de Vitoria","Batalla de Arapiles"],"correcta":"B","dificultad":3,"dato":"La Batalla de Medina de Rioseco (1808) se libró en tierras cercanas a Palencia, entre las tropas francesas de Bessiéres y el ejército español.","tiempo":20},
    {"id":54,"ronda":"profunda","categoria":"monumentos","pregunta":"¿Bajo qué reinado se construyó la mayor parte de la Catedral de Palencia?","opciones":["Reyes Católicos","Alfonso VIII","Sancho III de Castilla","Carlos V"],"correcta":"C","dificultad":3,"dato":"La Catedral de Palencia se inició en el s. XIV sobre una cripta visigoda y anterior románica, pero su impulso gótico principal fue durante el reinado de Sancho IV y posteriores.","tiempo":20,"verificar":true},
    {"id":55,"ronda":"profunda","categoria":"historia","pregunta":"¿Qué importancia tenía Carrión de los Condes en la Edad Media?","opciones":["Era un simple pueblo agrícola","Era sede de concilios y enclave clave del Camino de Santiago","Era la capital del reino de León","Era un puerto marítimo"],"correcta":"B","dificultad":2,"dato":"Carrión de los Condes fue una de las villas más importantes de la España medieval, sede de concilios y parada obligatoria del Camino de Santiago.","tiempo":20},
    {"id":56,"ronda":"profunda","categoria":"monumentos","pregunta":"¿Qué elemento escultórico destaca en la portada de la iglesia de San Martín de Frómista?","opciones":["Un Pantocrátor con tetramorfos","Un Cristo crucificado gótico","Un retablo barroco","Un mosaico bizantino"],"correcta":"A","dificultad":3,"dato":"La portada de San Martín de Frómista destaca por su Pantocrátor rodeado del tetramorfos (símbolos de los evangelistas), obra cumbre del románico.","tiempo":20},
    {"id":57,"ronda":"profunda","categoria":"historia","pregunta":"¿Quién fue el arquitecto principal del Canal de Castilla?","opciones":["Vauban","Antonio de Ulloa","Fernando de Ulloa","Juan de Villanueva"],"correcta":"C","dificultad":3,"dato":"Fernando de Ulloa fue el ingeniero principal que dirigió las obras del Canal de Castilla en su fase inicial.","tiempo":20,"verificar":true},
    {"id":58,"ronda":"profunda","categoria":"naturaleza","pregunta":"¿Qué especie de urogallo se encuentra en peligro de extinción en Fuentes Carrionas?","opciones":["Urogallo cantábrico","Urogallo pirenaico","Gallo de las praderas","Faisán"],"correcta":"A","dificultad":3,"dato":"El urogallo cantábrico (Tetrao urogallus cantabricus) habita en Fuentes Carrionas y está en grave peligro de extinción.","tiempo":20},
    {"id":59,"ronda":"profunda","categoria":"historia","pregunta":"¿Qué personaje bíblico da nombre a la cripta de la Catedral de Palencia?","opciones":["San Pedro","San Antolín","San Pablo","San Juan"],"correcta":"B","dificultad":3,"dato":"La Cripta de San Antolín, bajo la catedral, es el resto más antigro del edificio, con origen visigodo.","tiempo":20},
    {"id":60,"ronda":"profunda","categoria":"monumentos","pregunta":"¿Qué colegiata románica se encuentra en la localidad de Husillos?","opciones":["Colegiata de San Pedro y San Pablo","Colegiata de Santa María la Mayor","Colegiata de San Miguel","Colegiata de Santa Eulalia"],"correcta":"A","dificultad":3,"dato":"La Colegiata de San Pedro y San Pablo de Husillos es un notable edificio románico del s. XI.","tiempo":20,"verificar":true},
    {"id":61,"ronda":"profunda","categoria":"historia","pregunta":"¿En qué año desapareció definitivamente la Universidad de Palencia?","opciones":["1208","1250","1345","1385"],"correcta":"B","dificultad":3,"dato":"La Universidad de Palencia entró en decadencia tras la muerte de Alfonso VIII y terminó desapareciendo hacia 1250, absorbida por la de Salamanca.","tiempo":20,"verificar":true},
    {"id":62,"ronda":"profunda","categoria":"personajes","pregunta":"¿Qué personaje histórico, conocido como el Cid, estuvo en tierras palentinas?","opciones":["Rodrigo Díaz de Vivar","Alfonso VI","Ramiro II","Fernán González"],"correcta":"A","dificultad":2,"dato":"Rodrigo Díaz de Vivar, el Cid Campeador, pasó por tierras palentinas en sus campañas, especialmente por Carrión de los Condes.","tiempo":20},
    {"id":63,"ronda":"profunda","categoria":"monumentos","pregunta":"¿Qué elementos decorativos son típicos del románico palentino en sus iglesias?","opciones":["Ajedrezados (taqueado jaqués) y canecillos","Azulejos mudéjares","Gárgolas góticas","Yeserías barrocas"],"correcta":"A","dificultad":2,"dato":"El románico palentino se caracteriza por el uso del ajedrezado (taqueado jaqués) en impostas y canecillos con figuras en los aleros.","tiempo":20},
    {"id":64,"ronda":"profunda","categoria":"historia","pregunta":"¿Qué papel jugó Palencia durante la Guerra Civil Española?","opciones":["Frente de batalla activo","Retaguardia republicana","Zona nacional desde el inicio","Territorio internacional"],"correcta":"B","dificultad":3,"dato":"Palencia quedó en zona nacional desde los primeros días de la Guerra Civil en julio de 1936.","tiempo":20,"verificar":true},
    {"id":65,"ronda":"profunda","categoria":"naturaleza","pregunta":"¿Qué río da nombre al Parque Natural de Fuentes Carrionas?","opciones":["Río Pisuerga","Río Carrión","Río Esla","Río Cea"],"correcta":"B","dificultad":3,"dato":"El Parque Natural toma su nombre de las fuentes del río Carrión, que nace en esta zona montañosa del norte de Palencia.","tiempo":20},

    # ===================== RONDA DESAFÍO (15) =====================
    {"id":66,"ronda":"desafio","categoria":"gastronomia","pregunta":"RETO: Nombra 3 pueblos de la Montaña Palentina en 5 segundos. ¿Cuál de estos NO pertenece a la Montaña Palentina?","opciones":["Cervera de Pisuerga","Guardo","Ampudia","Aguilar de Campoo"],"correcta":"C","dificultad":2,"dato":"Ampudia pertenece a la comarca de Tierra de Campos, no a la Montaña Palentina.","tiempo":15},
    {"id":67,"ronda":"desafio","categoria":"monumentos","pregunta":"RETO: ¿Cuántas iglesias románicas hay aproximadamente en la provincia de Palencia?","opciones":["Menos de 50","Entre 100 y 200","Más de 300","Más de 600"],"correcta":"D","dificultad":3,"dato":"Palencia es la provincia con más arte románico de España, con más de 600 iglesias románicas catalogadas.","tiempo":15},
    {"id":68,"ronda":"desafio","categoria":"historia","pregunta":"RETO RÁPIDO: ¿Verdadero o falso? El lechazo de Castilla y León tiene Indicación Geográfica Protegida.","opciones":["Verdadero","Falso"],"correcta":"A","dificultad":2,"dato":"El Lechazo de Castilla y León cuenta con IGP desde 2011, protegiendo esta denominación de calidad.","tiempo":10},
    {"id":69,"ronda":"desafio","categoria":"geografia","pregunta":"RETO: ¿Cuántos municipios tiene la provincia de Palencia aproximadamente?","opciones":["50","100","191","250"],"correcta":"C","dificultad":3,"dato":"La provincia de Palencia tiene 191 municipios, aunque muchos tienen menos de 100 habitantes.","tiempo":15},
    {"id":70,"ronda":"desafio","categoria":"deportes","pregunta":"RETO: ¿Qué ciclista palentino ganó etapas en la Vuelta a España?","opciones":["Carlos Sastre","Francisco Mancebo","Abraham Olano","Perico Delgado"],"correcta":"B","dificultad":3,"dato":"Francisco Mancebo, nacido en El Barraco (Ávila), no es palentino. Ninguno de los mencionados es de Palencia. El palentino más destacado fue Manuel Sanromà.","tiempo":15,"verificar":true},
    {"id":71,"ronda":"desafio","categoria":"tradiciones","pregunta":"RETO: ¿Qué tradición de Herrera de Pisuerga consiste en lanzar un muñeco de paja?","opciones":["El Judas","La Quinta","El Mayo","Las Luminarias"],"correcta":"A","dificultad":3,"dato":"En Herrera de Pisuerga se quema al 'Judas', un muñeco de paja, tradición que se celebra en Semana Santa.","tiempo":15,"verificar":true},
    {"id":72,"ronda":"desafio","categoria":"monumentos","pregunta":"RETO: ¿Qué villa palentina fue declarada Conjunto Histórico-Artístico por su arquitectura mudéjar?","opciones":["Ampudia","Becerril de Campos","Medina de Rioseco","Támara de Campos"],"correcta":"A","dificultad":3,"dato":"Ampudia fue declarada Conjunto Histórico-Artístico, destacando su castillo y su arquitectura histórica.","tiempo":15},
    {"id":73,"ronda":"desafio","categoria":"cultura_pop","pregunta":"RETO: ¿Qué serie de TVE grabó escenas en el Canal de Castilla a su paso por Palencia?","opciones":["El Ministerio del Tiempo","Águila Roja","Isabel","El tiempo entre costuras"],"correcta":"A","dificultad":3,"dato":"El Ministerio del Tiempo grabó escenas en el Canal de Castilla y otros lugares de la provincia de Palencia.","tiempo":15,"verificar":true},
    {"id":74,"ronda":"desafio","categoria":"historia","pregunta":"RETO: ¿Qué importantísima villa medieval fue capital del condado de Monzón y cuna de Alfonso VIII?","opciones":["Palencia","Carrión de los Condes","Valladolid","Burgos"],"correcta":"A","dificultad":3,"dato":"Hay fuentes que sitúan la corte del condado de Monzón en tierras palentinas, donde se educó Alfonso VIII.","tiempo":15,"verificar":true},
    {"id":75,"ronda":"desafio","categoria":"naturaleza","pregunta":"RETO: ¿Qué especie de buitre se puede observar en la Montaña Palentina?","opciones":["Buitre leonado","Cóndor","Buitre negro","Alimoche"],"correcta":"A","dificultad":2,"dato":"El buitre leonado es la especie de buitre más común en la Montaña Palentina, con importantes colonias.","tiempo":10},
    {"id":76,"ronda":"desafio","categoria":"gastronomia","pregunta":"RETO: ¿Con qué denominación de calidad cuenta la morcilla de Palencia?","opciones":["Denominación de Origen","Indicación Geográfica Protegida","Marca de Garantía","Sin protección especial"],"correcta":"C","dificultad":3,"dato":"La morcilla de Palencia cuenta con Marca de Garantía desde 2015.","tiempo":15,"verificar":true},
    {"id":77,"ronda":"desafio","categoria":"personajes","pregunta":"RETO: ¿Qué arquitecto palentino diseñó la Plaza Mayor de Palencia?","opciones":["Juan de Herrera","Ventura Rodríguez","Churriguera","Ninguno de los anteriores"],"correcta":"D","dificultad":3,"dato":"La Plaza Mayor de Palencia fue reformada en el s. XIX; no fue diseñada por los arquitectos mencionados. El ayuntamiento actual es obra de Jerónimo Arroyo.","tiempo":15,"verificar":true},
    {"id":78,"ronda":"desafio","categoria":"geografia","pregunta":"RETO: ¿Cuál es el pueblo más al norte de la provincia de Palencia?","opciones":["Triollo","Brañosera","Cervera de Pisuerga","San Cebrián de Mudá"],"correcta":"B","dificultad":3,"dato":"Brañosera, en el extremo norte de la provincia, es además considerado el municipio más antiguo de España (documentado desde 824).","tiempo":15},
    {"id":79,"ronda":"desafio","categoria":"datos_insolitos","pregunta":"RETO: ¿Qué récord tiene Brañosera (Palencia)?","opciones":["Municipio más antiguo de España","Pueblo más alto de Castilla y León","Municipio más pequeño de España","Primer pueblo con electricidad"],"correcta":"A","dificultad":2,"dato":"Brañosera es considerado el municipio más antiguo de España, con una carta puebla del año 824.","tiempo":10},
    {"id":80,"ronda":"desafio","categoria":"monumentos","pregunta":"RETO FINAL: ¿Cuántos metros de longitud tiene la Catedral de Palencia?","opciones":["80 metros","100 metros","130 metros","160 metros"],"correcta":"C","dificultad":3,"dato":"La Catedral de Palencia mide 130 metros de longitud, siendo la tercera más larga de España.","tiempo":15},
]

# Fix typo in id 52
for p in preguntas:
    if "difultad" in p:
        p["dificultad"] = p.pop("difultad")

os.makedirs('/home/daniel/.openclaw/workspace/projects/quiz-battle-palencia', exist_ok=True)

with open('/home/daniel/.openclaw/workspace/projects/quiz-battle-palencia/preguntas.json', 'w') as f:
    json.dump(preguntas, f, ensure_ascii=False, indent=2)

print(f"Generadas {len(preguntas)} preguntas")

# Generate markdown
md = "# Preguntas Quiz Battle - Palencia\n\n"
rondas = {"veloz": "⚡ Ronda Veloz", "imagen": "🖼️ Ronda Imagen", "curiosidades": "🤯 Ronda Curiosidades", "profunda": "🏔️ Ronda Palencia Profunda", "desafio": "🔥 Ronda Desafío"}
for ronda_key, ronda_name in rondas.items():
    ronda_qs = [p for p in preguntas if p["ronda"] == ronda_key]
    md += f"## {ronda_name} ({len(ronda_qs)} preguntas)\n\n"
    for q in ronda_qs:
        opts = "\n".join(f"  {'✅' if o == q['opciones'][['A','B','C','D'].index(q['correcta'])] else '❌'} {o}" for o in q['opciones'])
        md += f"**#{q['id']} [{q['categoria']}] {q['pregunta']}**\n{opts}\n\n💡 {q['dato']}\n\n"

with open('/home/daniel/.openclaw/workspace/projects/quiz-battle-palencia/preguntas.md', 'w') as f:
    f.write(md)

print("Markdown generado")
